USE sucos;
ALTER TABLE tabela_de_vendedor ADD PRIMARY KEY (MATRICULA);

ALTER TABLE tabela_de_vendedor ADD COLUMN (DATA_ADMISSÃO DATE);

ALTER TABLE tabela_de_vendedor ADD COLUMN (DE_FERIAS BIT);

INSERT INTO tabela_de_vendedores (MATRICULA,NOME,PERCENTUAL_COMISSAO,DATA_ADMISSAO,
DE_FERIAS) VALUES ( '00238','Pericles Alves',0.11,'2016-08-21',1);

INSERT INTO tabela_de_vendedores (MATRICULA,NOME,PERCENTUAL_COMISSAO,DATA_ADMISSAO,
DE_FERIAS) VALUES ( '00237','Roberta Martins',0.11,'2017-03-18',0)

INSERT INTO tabela_de_vendedores (MATRICULA,NOME,PERCENTUAL_COMISSAO,DATA_ADMISSAO,
DE_FERIAS) VALUES ( '00238','Pericles Alves',0.11,'2016-08-21',0)


